### ISSUE TITLE
Rename  repozitory

### ISSUE THREAD

**Issue by dark0ghost** [Debian/.github#11]
Renaming to Debian so that the text README appears as description (make this repozitory special)

**Comment by mapreri** [comment]
@dark0ghost I've done that, but it doesn't seem to have changed anything ?

(I don't know about what feature you might be talking about tbh)

**Comment by dark0ghost** [comment]
![Screenshot_20210201-172733_Chrome](https://user-images.githubusercontent.com/40036029/106471691-f4443880-64b2-11eb-8217-99b10cb520b6.jpg)


> @dark0ghost I've done that, but it doesn't seem to have changed anything ?
> 
> (I don't know about what feature you might be talking about tbh)
Here is the given function.  Must work.  Very strange.
![Screenshot_20210201-172733_Chrome](https://user-images.githubusercontent.com/40036029/106471834-19d14200-64b3-11eb-923b-5909130144a4.jpg)

**Comment by mapreri** [comment]
could it be that it's just for user profiles, and not orgs?

**Comment by dark0ghost** [comment]
[yes](https://dev.to/time2hack/this-is-how-you-can-activate-github-profile-readme-1n54) i was wrong for organizations it doesn't work yet

**Comment by mapreri** [comment]
I renamed it back for now.

**Comment by dark0ghost** [comment]
I came across an organization amethyst and their readme looks like this https://github.com/amethyst
![image](https://user-images.githubusercontent.com/40036029/149018848-f016ef7d-ccc4-4b28-baa7-1af00123e15b.png)
So it turns out if the repository is called <b>.github</b> move README.md to /profile/README.md and it will appear on the organization's profile!
![image](https://user-images.githubusercontent.com/40036029/149019074-ec46d86c-d24a-4278-9e9b-2aeca8fd50ed.png)

**Comment by mapreri** [comment]
ohhh, fancy.  I've now done it, thank you for the showing a working example! :)
