### ISSUE TITLE
please add umlaeute to the organisation

### ISSUE THREAD

**Issue by umlaeute** [Debian/.github#17]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hi, please add @umlaeute to the Github @Debian organisation.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEdAXnRVdICXNIABVttlAZxH96NvgFAmHoHIkACgkQtlAZxH96
NvgEfA/9EDa28F7ZrOVycG1gPtPA34VGorAoyba5vQfo8AiRJ/VRD9qTO0+hipue
OHvFSupRqak+YajkPwtor0auGnzmuDWpp8SJmo2Xth+PlrA9fMP1p6dWq8FY6gH/
WQ44D0avo4uDrhQftp2t1X9mtaZoeLQdvgnfILnp5vEyN8zwZELRLyXdl6W6287v
caZSMJ2SOEuotJIA9sUf75l8VHxxjkCwlyobwwiTKHlG8tknXC2WCpfwpvU7ZxzY
tOuHfO+L1r1FZ9CWhcR3fBkEp+l0JoYp6g0iCpjNV6owvzBOi+uMr7oKlZx7jFP8
+i4RydvXDzHCWXNqJSxM2PekyzY8XA8t/syFx6oy4seI3shx1ZApbap9Pu+Ylop0
wJAtjMhzLuL6rCgeV6HW2V8Qfwr5evYHLBAfgqdO8EKQQJ4/7hpOB9siklmUYTvm
qmUD94OSvT7f05wPw58DQ+z5GsjfYgBOu0dpAT4r6P/w7/Ns7oxfBqELHP9FGHxX
XqRti3J175oprlb58qbYg62zD7ICj/sGO/U5QVii9KmY95QkGOpJE3gyPvwKYrkR
8Dc+qFhWwzZZ3+Qf3XdUAKSkpifDfplooZ6kEjhqaJvXt7iWbaYt9W+FkS1KG8uB
+9rPIZLuDybY/BLhAzAMw5qj9qtNrR8gxKvLGar0Yx9hrIv0s0M=
=CPNp
-----END PGP SIGNATURE-----

**Comment by umlaeute** [comment]
while the README provides some instructions on how to apply for membership, it would be nice to have a "template" to ease the onboarding process (probably just some reference issue that is linked from the README. or even a [GitHub issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)).

for now, i've just followed the examples layed out in #6

**Comment by nthykier** [comment]
Invite sent.
