### ISSUE TITLE
A 

### ISSUE THREAD

**Issue by seamusdemora** [Debian/.github#23]
I have obtained a "source package" on my (RPi) platform using `apt-get source dhcpcd5`. I have made some modifications to the source files to correct a long-standing issue, re-built using `debuild` and done some testing.  I cannot (not allowed to) contribute my changes to the RPi repositories, and their timeline for a new release is unknown.

I'd like to make this revised source package available on my GitHub account. However I have noticed there are now binary files in the source package directory. I'm very new at this, but I doubt that these (binary) files & perhaps other files generated during `debuild` process should be uploaded to a GitHub repo; i.e. probably don't use `git add -A`. 

I'm posting here because after some research I cannot find anything relevant to my question, "How should a local 'source package' be pushed to a GitHub repo?"

**Comment by mapreri** [comment]
Hi,

This really is an inappropriate place for this kind of question.

May I recommend you write to https://lists.debian.org/debian-mentors/ to get help in submitting your contributions?

However, be aware that `dhcpcd5` is currently not really maintained, so even then getting your changes incorporated is not going to be trivial.
