### ISSUE TITLE
Modified 3rd party apps policy to be restricted by default

### ISSUE THREAD

**Issue by yarikoptic** [Debian/.github#3]
For interest to all @Debian/contributors , @Debian/dd-s-cron-users , @Debian/debian-developers , @Debian/debsources-admins , @Debian/developers 
I have outlined my concerns and howto in recent issue to scikit-learn: https://github.com/scikit-learn/scikit-learn/issues/6679 , and while at this "hunt" I have restricted permissions on @Debian organization while authorizing only Travis and Appveyor so far.  If you have used any other service which is needed to gain access to the repos under Debian organization, please enable it under your account in  https://github.com/settings/applications  or follow up to this issue and I would do it if you don't have enough permissions.

Cheers

**Comment by mapreri** [comment]
ack.
