### ISSUE TITLE
How do I join this organization?

### ISSUE THREAD

**Issue by venthur** [Debian/.github#6]
While the `README.Debian` states: 

> If you maintain a package whose upstream developers use GitHub, please feel free to join this group and mirror such project here.

it is unclear how to do that. Usually someone has to invite you to become a member of a github Org but it is not obvious **who** to ask. Maybe the `README.Debian` should provide a contact for requests like these?

**Comment by 0xaf1f** [comment]
I believe @charles-plessy is managing it.

**Comment by charles-plessy** [comment]
Yes, I do it by hand. I beleive that Yaroslav also answers requests when contacted. I am all for automation if somebody knows how to do it properly. Also, I have nothing against a periodic rotation of the admins.

**Comment by venthur** [comment]
@charles-plessy can you add [me](https://qa.debian.org/developer.php?login=venthur) to the Org? Also, could we setup some template for isses that deal with join-requests?

**Comment by charles-plessy** [comment]
Le Sun, Oct 08, 2017 at 10:09:19AM +0000, Bastian Venthur a écrit :
> 
> Also, could we setup some template for isses that deal with join-requests?

Patches welcome !

-- 
Charles

**Comment by nomadium** [comment]
Hi @charles-plessy, can you add me to the org? Thanks.

**Comment by charles-plessy** [comment]
Done; could you send me a signed email just to make 100% sure that the nomadium account is really you (that is, not ta third party trying to impersonate you). Not that I have any specific worry in your case, but I try to ask this systematically.

**Comment by nomadium** [comment]
@charles-plessy Thank you Charles. I just sent you a signed email to your @debian email address.

**Comment by paride** [comment]
Hello @charles-plessy, I maintain a few Debian packages [1], and for some of them the upstream source is maintained on GitHub. I would like to join this organization and use it to fork repositories and submit pull request (now I normally use my personal account). I can send you a PGP-signed email to your @debian.org account using my `Maintainer:` email, or you can trust keybase [2]. Just let me know.

Thank you,

Paride

[1] https://qa.debian.org/developer.php?login=pl%40ninthfloor.org
[2] https://keybase.io/paride

**Comment by charles-plessy** [comment]
Hi Paride, I added you provisionally, but please confirm your identity by sending me a signed email.

**Comment by yarikoptic** [comment]
@xinfinity0 why they interest to join? Describe please since we aren't personally familiar, aren't we?

**Comment by infinity0** [comment]
@yarikoptic I am a Debian Developer, you can find my key (the same key that signed the above message) in `/usr/share/keyrings/debian-keyring.gpg`.

~~~~
$ gpg --no-default-keyring --keyring /usr/share/keyrings/debian-keyring.gpg --verify <<eof
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA512
> 
> Hi, please add infinity0 to the Github debian organisation.
> -----BEGIN PGP SIGNATURE-----
> 
> iHUEARYKAB0WIQReYinNQ9GpZ9TYcRrrH8jaRfspMAUCXBaYwwAKCRDrH8jaRfsp
> MEwLAP9yMyPbRsKs1fJIJBS3211dTTk+5J1TNp40S0xOpxqJzAD8DlLU51KQ+i7H
> Pjm3zfnBBr7NPWyUk+9OHPbyORsQDAo=
> =pCXF
> -----END PGP SIGNATURE-----
> eof
gpg: Signature made Sun 16 Dec 2018 10:26:11 PST
gpg:                using EDDSA key 5E6229CD43D1A967D4D8711AEB1FC8DA45FB2930
gpg: Good signature from "Ximin Luo" [ultimate]
gpg:                 aka " <infinity0@pwned.gg>" [ultimate]
gpg:                 aka " <infinity0@debian.org>" [ultimate]
gpg:                 aka " <infinity0@torproject.org>" [ultimate]
gpg:                 aka " <infinity0@freenetproject.org>" [ultimate]
~~~~

**Comment by eriol** [comment]
Hello I'm a Debian Developer, please can you add me to this organization? Here my declaration of intent:
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hello, please add eriol to the Github Debian organization.
Several packages I maintain[¹] are on Github and I would like to
fork them here instead of using my personal account to provide patches
upstream. Thanks

[¹] https://qa.debian.org/developer.php\?login\=eriol
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEExlrvn+W/jMvW7bAZi69SLA1szt0FAlxoOIoACgkQi69SLA1s
zt3vOw//XZyGgC/HENVdrGcDK/3fVYrKSYAWItV2+N+/CirUkcsDMNiAtileOG3v
X9DDgKmnDKFA6a9Sfic3za0Phk9DUch/Pu3bK/Qc4jpQLd/DPuhzD5Ar89/RHJDb
UQLfGJzyrKNGlJNdaY+d3K9/qYjRU6I/MUAIrUZ3i0tCXTdNUxaWZ3PpYw9qmcG/
4ZPx5mfc+FNCkiimUsJHH+pDeXzZG+uEfw58mYr0QUAoTCdBxeBgNPStMGXip8FN
P9OL7qCTzezS8+eatIKypRO5C7wr23l+LNFhYGWUtbc3x6QZn57nrOv3dqVv6FDJ
eC4ao5YsrcEiFu4PbvL1nsn5hU5MzKyCk0WkGLtCoPPni//H1Q7ZSrbsLk899B5S
T5+aNHxwh7PHaYDWmWv9vgJaFhfdbUCoVsrb6DZSTDvZWJstSuNa9JVIi1bd5Q8N
ytXBkvxXD4CaCW6LneXD+TFRcpj76BzgHg+zUiI6SYd38T4ZF+kId28d2vaHZLeH
slqPiAGpGljof/qGRRJqUbG8sKJmSOKPOhGM3pRflVrzZxgoVtRtWQ3+aQtVOzgS
r3fZe3nasT55sPtxUWwqdYvcmHlDdFcbIwYBkf6eq26wyna9INJgJN453eqeCcDk
8OBvFArzcOKi5gxXbgRbS2bfWdMUHjhZ3YhTLihNFyN+nTO7Mr8=
=PCNq
-----END PGP SIGNATURE-----
```

The message is signed with the key I have in the Debian keyring:

```
$ gpg --no-default-keyring --keyring /usr/share/keyrings/debian-keyring.gpg --verify <<EOF
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA512
> 
> Hello, please add eriol to the Github Debian organization.
> Several packages I maintain[¹] are on Github and I would like to
> fork them here instead of using my personal account to provide patches
> upstream. Thanks
> 
> [¹] https://qa.debian.org/developer.php\?login\=eriol
> -----BEGIN PGP SIGNATURE-----
> 
> iQIzBAEBCgAdFiEExlrvn+W/jMvW7bAZi69SLA1szt0FAlxoOIoACgkQi69SLA1s
> zt3vOw//XZyGgC/HENVdrGcDK/3fVYrKSYAWItV2+N+/CirUkcsDMNiAtileOG3v
> X9DDgKmnDKFA6a9Sfic3za0Phk9DUch/Pu3bK/Qc4jpQLd/DPuhzD5Ar89/RHJDb
> UQLfGJzyrKNGlJNdaY+d3K9/qYjRU6I/MUAIrUZ3i0tCXTdNUxaWZ3PpYw9qmcG/
> 4ZPx5mfc+FNCkiimUsJHH+pDeXzZG+uEfw58mYr0QUAoTCdBxeBgNPStMGXip8FN
> P9OL7qCTzezS8+eatIKypRO5C7wr23l+LNFhYGWUtbc3x6QZn57nrOv3dqVv6FDJ
> eC4ao5YsrcEiFu4PbvL1nsn5hU5MzKyCk0WkGLtCoPPni//H1Q7ZSrbsLk899B5S
> T5+aNHxwh7PHaYDWmWv9vgJaFhfdbUCoVsrb6DZSTDvZWJstSuNa9JVIi1bd5Q8N
> ytXBkvxXD4CaCW6LneXD+TFRcpj76BzgHg+zUiI6SYd38T4ZF+kId28d2vaHZLeH
> slqPiAGpGljof/qGRRJqUbG8sKJmSOKPOhGM3pRflVrzZxgoVtRtWQ3+aQtVOzgS
> r3fZe3nasT55sPtxUWwqdYvcmHlDdFcbIwYBkf6eq26wyna9INJgJN453eqeCcDk
> 8OBvFArzcOKi5gxXbgRbS2bfWdMUHjhZ3YhTLihNFyN+nTO7Mr8=
> =PCNq
> -----END PGP SIGNATURE-----
> EOF
gpg: Signature made Sat 16 Feb 2019 05:21:30 PM CET
gpg:                using RSA key C65AEF9FE5BF8CCBD6EDB0198BAF522C0D6CCEDD
gpg: Good signature from "Daniele Tricoli <eriol@mornie.org>" [ultimate]
```

**Comment by eriol** [comment]
@yarikoptic ↑

**Comment by charles-plessy** [comment]
@eriol Done, sorry for making you wait!

**Comment by eriol** [comment]
@charles-plessy many thanks, and no problem!

**Comment by olebole** [comment]
Could you add me as well please? Here is the signed (by olebole@d.o) request:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi, please add me (olebole) to the Github debian organisation.
-----BEGIN PGP SIGNATURE-----

iF0EARECAB0WIQTFQD+G9M9b466qYxkhFT9bCdYi/AUCXMlh4wAKCRAhFT9bCdYi
/LXSAJ9MTkufuhkX/mUvM3rhVDaxuX+zOgCgglCkVfa+PY6EzF3oHctXRc2rdLk=
=amzQ
-----END PGP SIGNATURE-----
```

**Comment by olebole** [comment]
ping

**Comment by merkys** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please add me (merkys) to the GitHub Debian organization.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEdyKS9veshfrgQdQe5fQ/nCc08ocFAl9Iu3sACgkQ5fQ/nCc0
8odPjA/7BbFf9sxxoCaFgcXFJINCoDXw3bJzxVfWpkYu/CfbW/b+eEX+ihwvPA+z
swmoWJBsTUTClztBhWd4RUp6pJhQrupwBdAE9TYCwLPsiRrORHz3sq83e37Ph/4p
T8WK4tBenExK9GAjJrIygIqKTflb+pZKSJOihkFUeCfhe0hgljVDJ1j/o8xXaF9K
ETqF7QwJVcn/gCX8T0eafD7KPuFDlC9VCjvH+IOn2qQeVvOOMtnbToUWmei+OVIH
sMAtyzfxESN0pguKw7LqL8cLXy99glL8Hpzkl28kMDG8E5qUKrb5n0DKWuQ4DbYc
0eV1nqgp8Xlo8AEZRK9R9UFz4QHREEsf5vD3yJw6SwXRq4grF3YJ+16CGFW/eOfz
sa8uvQGpNhoQPnI5Rz6bzp6HbrAdYy1g0DNovGGhgeA8b23+BvKHmEJi7NbnSEb1
huS/QmYxem/Az8p3+zDGc+jCw1W7JMpBEg+qYOXUudC4X62YhIhdSR83SwTbxstb
fALIcGjBTMh+UigWQOKbJeG2h4GKKBiT0KwkmQCwEnGR6cz41h/UYKdC30oVuOnp
1dBw0rrcuOhyyq6b+PX9D80XwzylElOwL9LFtF9rokzqZljvMnyK823jycPU8Xv7
DMnPgaznyd528crPc672eqHFrSBdYsqgb3IVzoYhSeuZg/CSwyo=
=Luui
-----END PGP SIGNATURE-----
```

**Comment by merkys** [comment]
Thanks a lot @charles-plessy!

**Comment by aweeraman** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi @charles-plessy, requesting to be added to this org.
thanks.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE9WuPFOAUze9dBH/BY221odkYYP0FAmDMhRsACgkQY221odkY
YP2P+A//c+u0A32m7BsEV9WwF3o7ll0e3zsSyp4FevWXhclkw/MBxHDt30yAz4CU
CYtz+6XyjcKuDzGH6KzjjadJvGe9x5iyuI+3hZILikY5hYvnQ2v9j8m7VGRlnev3
8fuC+f6KKfUdD7p9PWb9Lm7dH8gkva6TIR56lLn/AHvSEUMOon7eDNVddyQ3RHsG
aKxxM9o02VbMcFp05o7Ga7EWF3IlBknRZEe5J+sx4Y0Q0VoEG6cP78pFRcAG1SVU
9a/7auB2aTtllUrj80510oG2rJ7VLzsYR0QqaCG6xFJ/IdwkI9EmutDuLcw2bnVz
LuFySyioQriK93R3BVu80PVwML9elm8UZw1FdKbvTLQQUYf7E2F2+oluPih2JF2t
Sgqo1VxVflh/DYE6GQFW0UpwzBAEuiwXAMFoijaDu0u8nF1VGucPzBSNdFbRXyUB
M5PAbqQEdMWHLTQH89E8jvbkIQxzJa8kROYUIV1A7q3xfqql41K3xuQKzEYI4UZC
NCNIk95AkLuiZmBsaLbJFWT6Sy+cz5rW3t51Nvk4pXl96o+MxjiMMbfYZ04oKcdD
df4C3UX7SD7MXPPVekVCRINZb1XT7ZdQ1BMJtZkXo3cYxGUDUMbbXriUrVdeHNNW
xrwV0rUNuZiQvXrGgQt/aErsVxfWFXghWFUgdcO6QdWqmiat60A=
=pxFd
-----END PGP SIGNATURE-----

**Comment by dleidert** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please add me (dleidert) to this org.
-----BEGIN PGP SIGNATURE-----

iQJIBAEBCgAyFiEEvu1N7VVEpMA+KD3HS80FZ8KW0F0FAmGSS2gUHGRsZWlkZXJ0
QGRlYmlhbi5vcmcACgkQS80FZ8KW0F0YMBAA0CReEtecq8hte6WE1HZNldosZtqo
ZoFidLWdzPAMNj7ZrjjPzZ2XfRmmL6tbjxHYPwdTx2CK/Z6HpJS50WgIygUwmVdG
O+eQMnEu99rmGXLoqWGiGrGX9S8eNVwftkEhVUCdgsgwmtJvQZgC+Ye3u8m1Bn55
FUzkKbFQ2jiO9u/EJjpYDAYdiTbkkzynXDtv9sqiRtWDediLJ6C/2dl1AEHwU9CA
Epn8mIGMRFGbkA5R7Y2nM+EFX8DWsBhFOz6EtNZVwkTv6A+7AnHDhwLqFiXXZT/G
2iElqZ48dcJ0zwlCE2RCsQCVs8zW96b7HB8HhXf9+/xIf8zuaiuogcqsyBssz6uz
zyQcckW2yLdVxkU5y5EFuTKTqSGeRE95jYL4FATDzrGd/VVnK+RacABgOwjdvyvD
HoH9wmaLmBfIBVo/RdysL7JLUPdfLi78FsQt20IuBdZahcEORyUxX/I+RfBNgZaV
77BmRku/fbimJmAJ2QFRPnRQTHHC27efnkEhX8j6rlE8MUBMqyLXw/Vqmekf6cNQ
0Vjx2ZSZlfvAbJx5mP7iY9YqvsbxBl0xOK30FWiARf+JIp3bIUboCmJ3Od3be5x6
iUEoCtvifz0Uxl41AwljGOsBA3Pwo0whC3BBWgWZkrfIfAb+ec7GEOFF2pnYw7+L
aDfWnJx1c2mRRCQ=
=SAOr
-----END PGP SIGNATURE-----

**Comment by stephanlachnit** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please add me (stephanlachnit) to the GitHub Debian organization.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEu0Wws/9WG9vUXuips1tJ6l1WPv4FAmHYupAACgkQs1tJ6l1W
Pv52Yg//cnBARArOvc3mXkkKG50lj3hO5grbzbfn32ezCfSeYL45QbfCKXouq24n
MPREKB0HDbAnKlEzbL+ed+tbZgQya9lsQkRipVbBK0G6iimy1Vymy6RkJU8s2Uti
k/YNPh2b32zC0zWpSBaBA6OPXK1YdkAZ5XQBgvTMSeGDaOZan9OXVORtJY3vihk5
CAt+MR/WafOLhLdRw6ObYF/jZ7iPTBfVt2nJkB5EocAe44bwpVGyvHgqXnvO8Qe0
yO/9auvAcQrgyVD40PNTdYfW6g+QNToVEye0FgVZqBLVipfZgpiSWOnWkJSs+FGT
an0zy5caGbiXUszSNKa8ZRitr0ncw+z7d0RH426PtksBlp48KUavcfp7VES/aJEF
7bNrH5oZxHUVgdnSffPwehuIeiBNFXPvQL5jo3Y9uhmJKMwR3GEfkK13JkVwUy1C
n0nckkiw9OdkxcfFn9KYHv8vpJL7QICbntHkqdGPArkTyigUKeaxpAwk4OC5UfbS
RvEFnzdtIHETY77d+rKlzIC8rxYinb3aeIuHRTlsBS/VSQFZYU+tqPYvT008u3v+
Y86xETEral31CAkO+fhQurkoWKPVhWurz/OK8lxQcmCyYg/l9YXjpVGP66+ENLY/
AxzTYqjfYqb8NQnXJqVybEOw1obfSqVpumKgvuLzsZ/mlqtF1kc=
=2CPM
-----END PGP SIGNATURE-----

**Comment by mapreri** [comment]
Following https://github.com/Debian/.github/issues/5 and 3a323e1ec362d7bad8553f7940eba7b75f76ae12 - I'm closing this issue.

New people wanting to join please open your own ticket.
