### ISSUE TITLE
please add me to this organization

### ISSUE THREAD

**Issue by jmw-debian** [Debian/.github#65]
### Your signed membership application

```plain text
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please add me (Debian user (jmw@debian.org} to this organization
-----BEGIN PGP SIGNATURE-----

iHUEARYKAB0WIQTdFzjfLGn8URFmteMDXuYJgEtROQUCZyi5ZAAKCRADXuYJgEtR
OU0wAQCy4w8RO/mjqqwKbN0NB8NOUmaEQy64TUp5G3ZKdTD7lQEAh2OQa4wgCTdo
3UYP0pAed7IcO/4N/8z40Q5KbO3J7A0=
=LuKx
-----END PGP SIGNATURE-----
```

**Comment by umlaeute** [comment]
seems like @jmw-debian you did an incomplete paste: the first line should read `-----BEGIN PGP SIGNED MESSAGE-----` but really did read `PGP SIGNED MESSAGE-----`, which makes the message not verifiable.

i've fixed the first line, hoping that the bot would re-run, but apparently not.
anyhow, I've manually verified the signature (with the fixed header), which was indeed made by `jmw@debian.org`

I've re-opened this ticket so @charles-plessy (or somebody else who has the powers) can add you at their earliest convenience.

**Comment by charles-plessy** [comment]
Thanks for the help.  I just tried to verify the signature too and it gave:

```
-----END PGP SIGNATURE-----
gpg: Signature made Mon 04 Nov 2024 09:09:08 PM JST
gpg:                using EDDSA key DD1738DF2C69FC511166B5E3035EE609804B5139
gpg: Can't check signature: No public key
```

Pardon me to be so clumsy with GPG, but can you explain me how to compare this result with `CA619D65A72A7BADFC96D280196418AAEB74C8A1`, which is what <https://db.debian.org> reports for Jonathan?

Charles

**Comment by umlaeute** [comment]
@charles-plessy i've added an explanation to #32

**Comment by charles-plessy** [comment]
Invitation sent!
